""".docbot/ project directory management.

Handles initialisation, discovery, and config/state I/O for the persistent
``.docbot/`` directory that lives at the root of a documented repository.
"""

from __future__ import annotations

import json
import tomllib
from pathlib import Path

from .models import DocbotConfig, ProjectState

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_GITIGNORE = """\
# Auto-generated by docbot -- only config.toml is tracked.
*
!config.toml
!.gitignore
"""

_SUBDIRS = ("docs", "docs/modules", "scopes", "history")

# ---------------------------------------------------------------------------
# Initialisation
# ---------------------------------------------------------------------------


def init_project(path: Path) -> Path:
    """Create a ``.docbot/`` directory with default config and .gitignore.

    *path* should be the repository root (must contain a ``.git/`` directory).
    Returns the full path to the newly created ``.docbot/`` directory.

    Raises ``FileExistsError`` if ``.docbot/`` already exists.
    Raises ``ValueError`` if *path* is not a git repository.
    """
    path = path.resolve()
    if not (path / ".git").is_dir():
        raise ValueError(f"{path} is not a git repository (no .git/ directory)")

    docbot_dir = path / ".docbot"
    if docbot_dir.exists():
        raise FileExistsError(f"{docbot_dir} already exists")

    docbot_dir.mkdir()
    for sub in _SUBDIRS:
        (docbot_dir / sub).mkdir(parents=True, exist_ok=True)

    save_config(docbot_dir, DocbotConfig())
    (docbot_dir / ".gitignore").write_text(_DEFAULT_GITIGNORE, encoding="utf-8")

    return docbot_dir


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------


def find_docbot_root(start: Path) -> Path | None:
    """Walk *start* and its parents looking for a ``.docbot/`` directory.

    Returns the **project root** (the parent of ``.docbot/``), or ``None``
    if no ``.docbot/`` directory is found.
    """
    current = start.resolve()
    for d in [current, *current.parents]:
        if (d / ".docbot").is_dir():
            return d
        # Stop at filesystem root (handled by parents exhaustion).
    return None


# ---------------------------------------------------------------------------
# Config I/O (TOML)
# ---------------------------------------------------------------------------


def load_config(docbot_dir: Path) -> DocbotConfig:
    """Read ``.docbot/config.toml`` and return a ``DocbotConfig``.

    Returns defaults if the file is missing or unparseable.
    """
    config_path = docbot_dir / "config.toml"
    if not config_path.is_file():
        return DocbotConfig()
    try:
        with config_path.open("rb") as f:
            data = tomllib.load(f)
        return DocbotConfig(**data)
    except Exception:
        return DocbotConfig()


def save_config(docbot_dir: Path, config: DocbotConfig) -> None:
    """Write a ``DocbotConfig`` to ``.docbot/config.toml``."""
    lines = [
        f'model = "{config.model}"',
        f"concurrency = {config.concurrency}",
        f"timeout = {config.timeout}",
        f"max_scopes = {config.max_scopes}",
        f"max_snapshots = {config.max_snapshots}",
        f"no_llm = {'true' if config.no_llm else 'false'}",
    ]
    (docbot_dir / "config.toml").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


# ---------------------------------------------------------------------------
# State I/O (JSON)
# ---------------------------------------------------------------------------


def load_state(docbot_dir: Path) -> ProjectState:
    """Read ``.docbot/state.json`` and return a ``ProjectState``.

    Returns an empty ``ProjectState`` if the file is missing or corrupt.
    """
    state_path = docbot_dir / "state.json"
    if not state_path.is_file():
        return ProjectState()
    try:
        return ProjectState.model_validate_json(
            state_path.read_text(encoding="utf-8")
        )
    except Exception:
        return ProjectState()


def save_state(docbot_dir: Path, state: ProjectState) -> None:
    """Write a ``ProjectState`` to ``.docbot/state.json``."""
    (docbot_dir / "state.json").write_text(
        state.model_dump_json(indent=2), encoding="utf-8"
    )
